clean: true
author: Joshua Emmons
author_url: https://uptake.com
github_url: https://github.com/UptakeMobile/uptake-networking-ios
module: UptakeNetworking
root_url: https://mobile-toolkit-docs.services.common.int.uptake.com/docs/uptake-networking-ios/

# custom_categories:
#   - name: Helpers
#     children:
#     - ErrorHelper
#   - name: Factories
#     children: 
#     - Logging
    
